### ISSUE TITLE
Task Error

### ISSUE THREAD

**Issue by Hacker-2022** [MeoMunDep/Birds-Sui#6]
Due to some issues the Bot is not able to complete any single task 😕

**Comment by MeoMunDep** [comment]
screenshot, just say not solve anything

**Comment by Hacker-2022** [comment]
First of all thanks for responding ☺️. And here is a refference attachment below. 

https://github.com/user-attachments/assets/bdf1c7db-6eb0-427d-bb78-5648370ad981

**Comment by MeoMunDep** [comment]
okay bro, i will workin on it, next time i wont reply, i will drop a heart icon for you that u can know i read the issues.

because i recieve many message in a day, anw tks u

**Comment by Hacker-2022** [comment]
Thanks mate... I saw the first ever guy on GitHub who responds so quick.... Love your projects 🤌🏻. And that's totally ok if you just drop an icon. 😁
